// Data loader that tries to load from JSON file, falls back to sample data
import { sampleData } from "./sampleData";

let cachedData = null;

export async function loadData() {
  if (cachedData) {
    return cachedData;
  }

  try {
    // Try to load from public/data.json (generated by Python export function)
    const response = await fetch("/data.json");
    if (response.ok) {
      const data = await response.json();
      cachedData = data;
      return data;
    }
  } catch (error) {
    console.warn("Could not load data.json, using sample data:", error);
  }

  // Fall back to sample data
  cachedData = sampleData;
  return sampleData;
}

